-- MySQL 建表示例：操作日志表（简化版，可按需裁剪/加索引）
CREATE TABLE IF NOT EXISTS `easy_log_record` (
  `id`              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `platform`        VARCHAR(64)     DEFAULT NULL COMMENT '平台/服务名',
  `operator`        VARCHAR(128)    DEFAULT NULL COMMENT '操作者',
  `operate_time`    DATETIME        NOT NULL     COMMENT '操作时间',
  `biz_no`          VARCHAR(128)    DEFAULT NULL COMMENT '业务标识（如订单号）',
  `module`          VARCHAR(64)     DEFAULT NULL COMMENT '模块',
  `type`            VARCHAR(64)     DEFAULT NULL COMMENT '操作类型',
  `content`         VARCHAR(1024)   DEFAULT NULL COMMENT '操作内容（渲染后）',
  `content_param`   JSON            DEFAULT NULL COMMENT '内容占位符实参（数组）',
  `execute_time`    BIGINT          DEFAULT NULL COMMENT '耗时(ms)',
  `success`         TINYINT(1)      DEFAULT NULL COMMENT '是否成功',
  `result`          MEDIUMTEXT      DEFAULT NULL COMMENT '返回结果JSON',
  `error_msg`       VARCHAR(2048)   DEFAULT NULL COMMENT '错误信息',
  `stack_trace`     MEDIUMTEXT      DEFAULT NULL COMMENT '异常堆栈',
  `ip`              VARCHAR(64)     DEFAULT NULL COMMENT '请求IP',
  `url`             VARCHAR(512)    DEFAULT NULL COMMENT '请求URL',
  `http_method`     VARCHAR(16)     DEFAULT NULL COMMENT 'HTTP方法',
  `class_method`    VARCHAR(256)    DEFAULT NULL COMMENT '类.方法',
  `param_json`      MEDIUMTEXT      DEFAULT NULL COMMENT '方法参数JSON',
  `before`          MEDIUMTEXT      DEFAULT NULL COMMENT '变更前快照（用于字段对比）',
  `after`           MEDIUMTEXT      DEFAULT NULL COMMENT '变更后快照（用于字段对比）',
  `extra`           MEDIUMTEXT      DEFAULT NULL COMMENT '扩展信息（不参与对比）',
  `field_info_json` MEDIUMTEXT      DEFAULT NULL COMMENT '差异字段JSON',
  `created_at`      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_biz_no_time` (`biz_no`, `operate_time`),
  KEY `idx_platform_module_time` (`platform`, `module`, `operate_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='操作日志表';
